name: 'Momentic Run Tests'
description: 'GitHub Action to run tests on Momentic'
author: 'Momentic'

inputs:
  test-id:
    description: 'ID of the test to run'
    required: true

runs:
  using: node20
  main: dist/index.js
